### PR TITLE
Support linux mint

### PR DESCRIPTION
**Pull request by SimonLammer**
I'm not sure whether there is a cleaner way to do this. Anyhow, this works and introduces the least changes.

Basically: Use the appropriate ubuntu repo on linux mint distros.

### CODE REVIEW

**Comment by SimonLammer** [comment]
.

**Comment by SimonLammer** [comment]
@geerlingguy Are there any changes required before this can be merged?

**Comment by SimonLammer** [comment]
still relevant.

**Comment by Guergeiro** [comment]
Yup. Relevant for me as well. At the moment, I have to manually work around for it to work on mint systems.

**Comment by SimonLammer** [comment]
@geerlingguy

**Comment by SimonLammer** [comment]
.

**Pull request closed without merging**
