### PR TITLE
Fix apt errors on Pop!_OS

### LINKED ISSUE #382: Task 'Add Docker apt key' fails on Pop_OS! 22.04
Love this role! I'm trying to use it to get docker up and running on my new desktop, I see that there was a fix rolled in a couple months ago to address the deprecation of adding gpg keys. My system tries that task because I get a 404 in the `Add Docker apt key` task which is supposed to write to `/etc/apt/trusted/gpg.d/docker.asc`.

OS: Pop_OS! 22.04
ansible version: 2.10.8

```
TASK [geerlingguy.docker : Add Docker apt key.] *******************************************************************************************
task path: /home/nic/.ansible/roles/geerlingguy.docker/tasks/setup-Debian.yml:28
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: nic
<127.0.0.1> EXEC /bin/sh -c 'echo ~nic && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/nic/.ansible/tmp `"&& mkdir "` echo /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354 `" && echo ansible-tmp-1666793580.0911322-1284764-100212532572354="` echo /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/get_url.py
<127.0.0.1> PUT /home/nic/.ansible/tmp/ansible-local-1283842nmp4rqwc/tmpj2i8e42x TO /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354/AnsiballZ_get_url.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354/ /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354/AnsiballZ_get_url.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=piynqceudsljhelgfcpsenhouvoqrzbj] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-piynqceudsljhelgfcpsenhouvoqrzbj ; /usr/bin/python3 /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354/AnsiballZ_get_url.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/nic/.ansible/tmp/ansible-tmp-1666793580.0911322-1284764-100212532572354/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "dest": "/etc/apt/trusted.gpg.d/docker.asc",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "dest": "/etc/apt/trusted.gpg.d/docker.asc",
            "force": true,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": "0644",
            "owner": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": false,
            "url": "https://download.docker.com/linux/pop!_os/gpg",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Request failed",
    "response": "HTTP Error 404: Not Found",
    "status_code": 404,
    "url": "https://download.docker.com/linux/pop!_os/gpg"
}


```

### PR DESCRIPTION
**Pull request by dale-c-anderson**
Tested on Pop!_OS 22.04, but this is a tiny fix which should work for any version (of pop or mint). 

Closes #382 
Closes #334

### CODE REVIEW

**Comment by Guergeiro** [comment]
This is somewhat relevant to #334 
Maybe having a consistent way of targeting Ubuntu based distros instead of conditionally chaining all logic.
For instance, I know that Linux Mint has a `/etc/upstream-release/lsb-release`.

**Comment by dale-c-anderson** [comment]
@Guergeiro This could potentially be done more cleanly with a lookup table, but the real issue here is that there is no way to get the string `ubuntu` out of ansible facts for these distributions, so there's going to be some conditional logic no matter how you slice it. If you can demonstrate how parsing config files (which may or may not be present) is going to be cleaner than that, I'll buy you a beer. 

I added support for Linux Mint to my PR.  So now this can close #334 as well.

**Comment by geerlingguy** [comment]
The question I have is where is `docker_apt_ansible_distribution` defined?

**Comment by dale-c-anderson** [comment]
@geerlingguy Line 36 - though the way github highlights the diff by default, it's not all that easy to spot - https://github.com/geerlingguy/ansible-role-docker/pull/396/files#diff-23e21b6c89468f7534697ad091835b3ee5e0213b37ace489488234e5a9548ec4R36

**Comment by dale-c-anderson** [comment]
I see there's conflicts, which I'll get fixed up today.

**Pull request merged**
