### PR TITLE
Add CI for Fedora41

### PR DESCRIPTION
**Pull request by cschindlbeck**

### CODE REVIEW

**Comment by geerlingguy** [comment]
Hmm, getting:

```
fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"gpg2\" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin"}
```

(Can you also drop `fedora40`?)

**Comment by cschindlbeck** [comment]
> (Can you also drop `fedora40`?)

Are you planning to deprecate fedora? I would like to use this role on fedora...

**Comment by geerlingguy** [comment]
@cschindlbeck no, just like testing only on current Fedora version to save CI bandwidth.

**Comment by cschindlbeck** [comment]
I will run molecule locally instead of stealing CI bandwidth and reopen when ready...

**Pull request closed without merging**
