### PR TITLE
Alpine support

### PR DESCRIPTION
**Pull request by fourstepper**
This pull request brings Alpine Linux support to this Ansible role.

I am unsure how to add alpine to the CI as well, as you are probably using your own images judging by the Github CI file - a working image for a test/integration into the CI can be found here: https://hub.docker.com/r/fourstepper/docker-alpine312-ansible (I am not experienced with GitHub Actions so I didn't try to change the CI code)

### CODE REVIEW

**Comment by fourstepper** [comment]
Lint seems kind of strict to me, but can be changed if needed - CentOS failure seems unrelated

**Comment by geerlingguy** [comment]
CentOS failure is related to something else (it's failing in CI too).

**Comment by fourstepper** [comment]
I was wondering that when now its possible to test roles in Alpine with https://hub.docker.com/repository/docker/fourstepper/docker-alpine312-ansible if I could add that to the CI on my branch to see this pass? 

I am not sure if you are looking to merge this eventually or not. I know the management overhead could be larger, but I would be willing to help out if that's a problem.

**Comment by fourstepper** [comment]
Would it help if I added the latest stable docker image of alpine with openrc to the CI tests?

**Pull request closed without merging**
