### PR TITLE
Add daemon configuration

### PR DESCRIPTION
**Pull request by henyxia**
Signed-off-by: Jean Wasilewski <henyxia@revs0.com>

### CODE REVIEW

**Comment by henyxia** [comment]
@geerlingguy , any chance to see this PR merged? :)

**Comment by linuxbandit** [comment]
This addresses issue #90, and there are other PRs addressing it: #190, #140, #108 
(just wanted to make some order, hopefully one of the three will be picked. Trying to help with issue maintenance)

**Comment by felixb** [comment]
This is still relevant.

**Comment by linuxbandit** [comment]
This is still relevant indeed

**Pull request closed without merging**
