### PR TITLE
Change defaults for docker_apt_arch and docker_compose_arch to support armv7.

### PR DESCRIPTION
**Pull request by DecWebb**
Add conversion for armv7l to armv7 for compatibility with docker compose download architectures.
Replaces hardcoded "amd64" with ansible_architecture to support other architectures than amd64 and arm64.

### CODE REVIEW

**Comment by DecWebb** [comment]
I have fixed the build errors resulting from my change. I think some manual tests on different architectures to double check this change would be worthwhile.

**Comment by geerlingguy** [comment]
Is this for older Raspberry Pi installations? I pause when thinking of supporting non-64-bit OSes as Raspberry Pi themselves have finally moved on to 64-bit default for the Pi 5 (and 64-bit works on almost all Pi models now).

**Comment by DecWebb** [comment]
Yes, personally this is for an old rpi2b and also a Helios4 which is an armbian board. Both are 32bit and wont get 64bit OS support. I think its worthwhile while docker still supports 32bit os with the armhf binary (https://download.docker.com/linux/debian/dists/bookworm/stable/).

**Comment by DecWebb** [comment]
Closing as will not get merged, but useful for reference for others with older raspberry pi's and arm boards who run into errors using this role.

**Pull request closed without merging**
