### PR TITLE
Configure /etc/docker/daemon.json file

### PR DESCRIPTION
**Pull request by msirovy**
It allows user to configure docker https://docs.docker.com/config/daemon/

### CODE REVIEW

**Comment by robbyoconnor** [comment]
bumping to remove the staleness

**Comment by geerlingguy** [comment]
https://github.com/geerlingguy/ansible-role-docker/pull/256 existed prior to this PR. Is there anything in this particular PR that is added beyond what that PR was aiming to achieve.

I will be merging in support for daemon config soon (soon being a relative term...), but did you find anything in #256 to be incompatible with how you wanted to manage this file, or should I mark this a dupe and move efforts back to 256?

**Comment by robbyoconnor** [comment]
@geerlingguy  They look incompatible but I did glance quickly -- Honestly -- I think this one is better.

**Comment by geerlingguy** [comment]
Fixed via #256 — please see that issue for how it was implemented, and if there are any other changes in a follow-up, let me know.

**Pull request closed without merging**
